services:
  postgis:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_DB=postgres  
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=rrh44valDBinB7r1  
    ports: 
      - 5433:5432
    volumes:
      - ./data/postgis:/var/lib/postgresql/data